name: Publish Docker image

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ "main" ]
  workflow_dispatch:
  issues:
    types:
      - opened

jobs:
  push_to_registries:
    name: Push Docker image to github registry
    runs-on: [self-hosted, podman]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: Build image
        run: podman build -t j3sb/github-runner-podman .

      - name: Publish image
        run: podman push github-runner-podman j3sb/github-runner-podman
